server:
  port: 0

grpc:
  server:
    port: 59091
    reflection-service-enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: "recomm.collector"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.recomm.kafka.serializer.GeneralAvroSerializer

collector:
  kafka:
    producer:
      topics:
        user-actions: "stats.user-actions.v1"