grpc:
  server:
    port: 0

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.avro.serializer.GeneralAvroSerializer
      topics:
        user-action-topic: stats.user-actions.v1

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always