server:
  port: 0

spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/stats
    username: dbuser
    password: 12345

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: TRACE